### ISSUE TITLE
交易中 chainId不能设0，会被认为这个字段没设置

### ISSUE THREAD

**Issue by rink1969** [cryptape/web3.js#5]
最新版本交易里多加了chain id和version字段
刚升级到最新版本的时候，没设置chain id字段，导致报chainId exception
后来加上chain id，但是链的chain id是0，发现还是报chainId exception
后来把链的chain id改成1，发现就没问题了

**Comment by TheWaWaR** [comment]
chain id 为 0 时会随机给一个值，取值范围是 `[0, 2**29]`

**Comment by rink1969** [comment]
https://github.com/cryptape/web3.js/commit/7fd2295fdf57f2a09e0642b2d230dbe108dddca6
